### ISSUE TITLE
Enhance Frontend

### ISSUE THREAD

**Issue by dans77777** [obasekiosa/timly#11]

**Comment by dans77777** [comment]
need to add more spacing and flexibility between components

**Comment by xBis7** [comment]
Main method is on the app.java file and from there you are starting the stage. I removed the overriding from the MainWin so if you want to start the app right click on the App.java. I wrote the code about the results window check out the fonts, the spacing and all that to see how to make the MainWin look nicer.

**Comment by dans77777** [comment]
I also wrote code for spacing to make UI look nicer. Who's code to merge
now? 😶

**Comment by dans77777** [comment]
As you pushed change's to these  files.. It would be very conflicting to
merge my changes about UI.. So just send your screenshot of UI.. Let's see
who's looks better and will merge that one.

**Comment by dans77777** [comment]
@xBis7  see what i will do is..i will merge my changes with your changes n i will close the issue
ok?
