### ISSUE TITLE
Design classes and methods for finding intersecting time slots

### ISSUE THREAD

**Issue by obasekiosa** [obasekiosa/timly#6]
The project does not currently have a software design for its functionality this issue addresses that

**Comment by obasekiosa** [comment]
Hi @xBis7  so we  can talk about how to solve the issue right here

**Comment by xBis7** [comment]
I had an idea and I want your opinion. We will add three fields to Time.java class  
String startTime; 
String endTime;
String timezone; 
Time(); constructor for setting values 
getters

and we will create a list of Time objects and we will pass that list from the front to the back

**Comment by xBis7** [comment]
we will convert all timezones to GMT make all the calculation and return the desired gap in GMT 
we will also create a method for converting GMT to any other option
what do you think?

**Comment by xBis7** [comment]
Calculator.java

public list<Time> times;

public Calculator(list<Time> times){

}

for(int i=0; i<times.size(); i++){
String start = times.get(i).getStartTime();
String arr[] = start.split
long hour = arr[0];
}

**Comment by dans77777** [comment]
i added Datepicker first .javafx don't have dateTime

**Comment by dans77777** [comment]
Label description_label =
        new Label("This is a combo box example ");

// Weekdays
String week_days[] =
      { "IST", "GMT", "EST",
                       "UTC" };

// Create a combo box
ComboBox combo_box =
        new ComboBox(FXCollections
                    .observableArrayList(week_days));

// Create a tile pane
TilePane tile_pane = new TilePane(combo_box);
